const yargs = require('yargs/yargs')
const { hideBin } = require('yargs/helpers');
const argv = yargs(hideBin(process.argv))
    .command('play', 'Execute one or more tasks')
    .command('list', 'Show all tasks and steps')
    .command('help', 'Print help information')
    .boolean('version')
    .boolean('help')
    .boolean('verbose')
    .boolean('silent')
    .boolean('draw')
    .option('skip')
    .array('skip')
    .option('task')
    .array('task')
    .alias('V', 'version')
    .alias('?', 'help')
    .alias('v', 'verbose')
    .describe('verbose', 'Verbose mode')
    .describe('silent', 'Silent mode')
    .describe('skip', 'Specify task to skip')
    .describe('task', 'Specify task to execute')
    .describe('draw', 'Draw exectuion diagram')
    .usage('Usage: npx quest-runner <command> [options]')
    .epilog('If no task is specified, all tasks will be run.')
    .scriptName('')
    .help()
    .parse();
module.exports = argv;
